name: Docker_CLI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -   uses: actions/checkout@v4
    -   name: build container
        run: docker build -t interview .
    # - name: run tests
    #   uses: liatrio/github-actions/apprentice-action@master