name: Docker_CLI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -   uses: actions/checkout@v4
    # versioning using run id
    -   name: Build Container
        run: docker build -t interview_v:${{github.run_id}} .
    # push to Docker Hub using official Docker code
    -   name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{vars.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_TOKEN}}
    -   name: Set up QEMU
        uses: docker/setup-qemu-action@v3
    -   name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    -   name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: glrammer/technical_interview:${{github.run_id}}

